transitions = {
    'INITIAL':{
        'INITIAL':'INITIAL',
        '0': 'INTEGER5', 
        '1': 'INTEGER11',
        '2': 'INTEGER11', 
        '3': 'INTEGER6', 
        '4': 'INTEGER1', 
        '5': 'INTEGER1', 
        '6': 'INTEGER1', 
        '7': 'INTEGER1', 
        '8': 'INTEGER1', 
        '9': 'INTEGER1',
        'SY_OP':'SY_OP',
        'IDENT':'IDENT',
        'a': 'IDENT',
        'b': 'IDENTb',
        'c': 'IDENTc',
        'd': 'IDENTd',
        'e': 'IDENTe',
        'f': 'IDENTf',
        'g': 'IDENT',
        'h': 'IDENT',
        'i': 'IDENTi',
        'j': 'IDENT',
        'k': 'IDENT',
        'l': 'IDENTl',
        'm': 'IDENTm',
        'n': 'IDENTn',
        'o': 'IDENT',
        'p': 'IDENT',
        'q': 'IDENT',
        'r': 'IDENTr',
        's': 'IDENTs',
        't': 'IDENTt',
        'u': 'IDENT',
        'v': 'IDENTv',
        'w': 'IDENTw',
        'x': 'IDENT',
        'y': 'IDENT',
        'z': 'IDENT',
        'A': 'IDENT',
        'B': 'IDENT',
        'C': 'IDENT',
        'D': 'IDENT',
        'E': 'IDENT',
        'F': 'IDENT',
        'G': 'IDENT',
        'H': 'IDENT',
        'I': 'IDENT',
        'J': 'IDENT',
        'K': 'IDENT',
        'L': 'IDENT',
        'M': 'IDENT',
        'N': 'IDENT',
        'O': 'IDENT',
        'P': 'IDENT',
        'Q': 'IDENT',
        'R': 'IDENT',
        'S': 'IDENT',
        'T': 'IDENT',
        'U': 'IDENT',
        'V': 'IDENT',
        'W': 'IDENT',
        'X': 'IDENT',
        'Y': 'IDENT',
        'Z': 'IDENT',
        'UNDERSCORE':'IDENT',
        'NEWLINE':'NEWLINE',
        'BADTOKEN':'BADTOKEN',
        'SPACE':'SPACE',
        'SLASH':'SLASH',
        'QUOTE':'QUOTE',
        'STAR':'SY_OP',
        'SY_LPAREN':'SY_LPAREN',
        'SY_RPAREN':'SY_RPAREN',
        'SY_LBRACKET':'SY_LBRACKET',
        'SY_RBRACKET':'SY_RBRACKET',
        'SY_LBRACE':'SY_LBRACE',
        'SY_RBRACE':'SY_RBRACE',
        'SY_EQ':'SY_EQ',
        'SY_MINUS':'SY_MINUS',
        'SY_SEMI':'SY_SEMI',
        'SY_PERIOD':'SY_PERIOD',
        'SY_NOT':'SY_NOT',
        'SY_COMMA':'SY_COMMA',
        '*':'IDENT'},
    'QUOTE':{
        'NEWLINE':'INITIAL',
        '*':'QUOTE',
        'QUOTE':'STRING'},
    'IDENTb':{
        'o':'IDENTbo',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTbo':{
        'o':'IDENTboo',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTboo':{
        'l':'IDENTbool',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTbool':{
        'e':'IDENTboole',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTboole':{
        'a':'IDENTboolea',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTboolea':{
        'n':'KW_TYPE',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTc':{
        'h':'IDENTch',
        'o':'IDENTco',
        'l':'IDENTcl',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTch':{
        'a':'IDENTcha',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTcha':{
        'r':'KW_TYPE',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTcl':{
        'a':'IDENTcla',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTcla':{
        's':'IDENTclas',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTclas':{
        's':'KW_CLASS',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTco':{
        'n':'IDENTcon',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTcon':{
        's':'IDENTcons',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTcons':{
        't':'IDENTconst',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTconst':{
        'r':'IDENTconstr',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTconstr':{
        'u':'IDENTconstru',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTconstru':{
        'c':'IDENTconstruc',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTconstruc':{
        't':'IDENTconstruct',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTconstruct':{
        'o':'IDENTconstructo',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTconstructo':{
        'r':'KW_SUBDEC',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTd':{
        'o':'KW_DO',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTe':{
        'l':'IDENTel',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTel':{
        's':'IDENTels',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTels':{
        'e':'KW_ELSE',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTf':{
        'a':'IDENTfa',
        'i':'IDENTfi',
        'u':'IDENTfu',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfa':{
        'l':'IDENTfal',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfal':{
        's':'IDENTfals',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfals':{
        'e':'KW_CONST',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfi':{
        'e':'IDENTfie',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfie':{
        'l':'IDENTfiel',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfiel':{
        'd':'KW_VARDEC',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfu':{
        'n':'IDENTfun',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfun':{
        'c':'IDENTfunc',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfunc':{
        't':'IDENTfunt',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfunct':{
        'i':'IDENTfunti',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfuncti':{
        'o':'IDENTfuntio',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTfunctio':{
        'n':'KW_SUBDEC',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTi':{
        'f':'KW_IF',
        'n':'IDENTin',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTin':{
        't':'KW_TYPE',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTl':{
        'e':'IDENTle',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTle':{
        't':'KW_LET',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTm':{
        'e':'IDENTme',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTme':{
        't':'IDENTmet',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTmet':{
        'h':'IDENTmeth',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTmeth':{
        'o':'IDENTmetho',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTmetho':{
        'd':'KW_SUBDEC',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTn':{
        'u':'IDENTnu',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTnu':{
        'l':'IDENTnul',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTnul':{
        'l':'KW_CONST',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTr':{
        'e':'IDENTre',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTre':{
        't':'IDENTret',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTret':{
        'u':'IDENTretu',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTretu':{
        'r':'IDENTretur',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTretur':{
        'n':'KW_RETURN',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTs':{
        't':'IDENTst',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTst':{
        'a':'IDENTsta',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTsta':{
        't':'IDENTstat',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTstat':{
        'i':'IDENTstati',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTstati':{
        'c':'KW_VARDEC',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTt':{
        'r':'IDENTtr',
        'h':'IDENTth',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTtr':{
        'u':'IDENTtru',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTtru':{
        'e':'KW_CONST',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTth':{
        'i':'IDENTthi',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTthi':{
        's':'KW_CONST',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTv':{
        'a':'IDENTva',
        'o':'IDENTvo',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTva':{
        'r':'KW_VAR',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTvo':{
        'i':'IDENTvoi',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTvoi':{
        'd':'KW_VOID',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTw':{
        'h':'IDENTwh',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTw':{
        'h':'IDENTwh',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTwh':{
        'i':'IDENTwhi',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTwhi':{
        'l':'IDENTwhil',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'IDENTwhil':{
        'e':'KW_WHILE',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_IF':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_DO':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_TYPE':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_CLASS':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_SUBDEC':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_ELSE':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_VARDEC':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_LET':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_RETURN':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_VAR':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_VOID':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'KW_WHILE':{
        'QUOTE':'INITIAL',
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'INTEGER1': {
        '0': 'INTEGER2', 
        '1': 'INTEGER2', 
        '2': 'INTEGER2', 
        '3': 'INTEGER2', 
        '4': 'INTEGER2', 
        '5': 'INTEGER2', 
        '6': 'INTEGER2', 
        '7': 'INTEGER2', 
        '8': 'INTEGER2', 
        '9': 'INTEGER2',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'},
    'INTEGER2': {
        '0': 'INTEGER3', 
        '1': 'INTEGER3', 
        '2': 'INTEGER3', 
        '3': 'INTEGER3', 
        '4': 'INTEGER3', 
        '5': 'INTEGER3', 
        '6': 'INTEGER3', 
        '7': 'INTEGER3', 
        '8': 'INTEGER3', 
        '9': 'INTEGER3',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER3': {
        '0': 'INTEGER4', 
        '1': 'INTEGER4', 
        '2': 'INTEGER4',
        '3': 'INTEGER4', 
        '4': 'INTEGER4', 
        '5': 'INTEGER4', 
        '6': 'INTEGER4', 
        '7': 'INTEGER4', 
        '8': 'INTEGER4', 
        '9': 'INTEGER4',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER4': {
        '0': 'BADTOKEN', 
        '1': 'BADTOKEN', 
        '2': 'BADTOKEN', 
        '3': 'BADTOKEN', 
        '4': 'BADTOKEN', 
        '5': 'BADTOKEN', 
        '6': 'BADTOKEN', 
        '7': 'BADTOKEN', 
        '8': 'BADTOKEN', 
        '9': 'BADTOKEN',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER5': {
        '0': 'INTEGER5', 
        '1': 'INTEGER11',
        '2': 'INTEGER11', 
        '3': 'INTEGER6', 
        '4': 'INTEGER1', 
        '5': 'INTEGER1', 
        '6': 'INTEGER1', 
        '7': 'INTEGER1', 
        '8': 'INTEGER1', 
        '9': 'INTEGER1',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER6': {
        '0': 'INTEGER12', 
        '1': 'INTEGER12', 
        '2': 'INTEGER7', 
        '3': 'INTEGER3', 
        '4': 'INTEGER3', 
        '5': 'INTEGER3', 
        '6': 'INTEGER3', 
        '7': 'INTEGER3', 
        '8': 'INTEGER3', 
        '9': 'INTEGER3',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER7': {
        '0': 'INTEGER13', 
        '1': 'INTEGER13', 
        '2': 'INTEGER13', 
        '3': 'INTEGER13', 
        '4': 'INTEGER13', 
        '5': 'INTEGER13', 
        '6': 'INTEGER13', 
        '7': 'INTEGER8', 
        '8': 'INTEGER4', 
        '9': 'INTEGER4',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER8': {
        '1': 'INTEGER14', 
        '2': 'INTEGER14', 
        '3': 'INTEGER14', 
        '4': 'INTEGER14', 
        '5': 'INTEGER14', 
        '6': 'INTEGER9', 
        '7': 'INTEGER5', 
        '8': 'INTEGER5', 
        '9': 'INTEGER5',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER9': {
        '0': 'INTEGER15', 
        '1': 'INTEGER15', 
        '2': 'INTEGER15', 
        '3': 'INTEGER15', 
        '4': 'INTEGER15', 
        '5': 'INTEGER15', 
        '6': 'INTEGER15', 
        '7': 'INTEGER15',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'},
    'INTEGER11': {
        '0': 'INTEGER12', 
        '1': 'INTEGER12', 
        '2': 'INTEGER12', 
        '3': 'INTEGER12', 
        '4': 'INTEGER12', 
        '5': 'INTEGER12', 
        '6': 'INTEGER12', 
        '7': 'INTEGER12', 
        '8': 'INTEGER12', 
        '9': 'INTEGER12',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER12': {
        '0': 'INTEGER13', 
        '1': 'INTEGER13', 
        '2': 'INTEGER13', 
        '3': 'INTEGER13', 
        '4': 'INTEGER13', 
        '5': 'INTEGER13', 
        '6': 'INTEGER13', 
        '7': 'INTEGER13', 
        '8': 'INTEGER13', 
        '9': 'INTEGER13',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER13': {
        '0': 'INTEGER14', 
        '1': 'INTEGER14', 
        '2': 'INTEGER14', 
        '3': 'INTEGER14', 
        '4': 'INTEGER14', 
        '5': 'INTEGER14', 
        '6': 'INTEGER14', 
        '7': 'INTEGER14', 
        '8': 'INTEGER14', 
        '9': 'INTEGER14',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER14': {
        '0': 'INTEGER15', 
        '1': 'INTEGER15', 
        '2': 'INTEGER15', 
        '3': 'INTEGER15', 
        '4': 'INTEGER15', 
        '5': 'INTEGER15',
        '6': 'INTEGER15', 
        '7': 'INTEGER15', 
        '8': 'INTEGER15', 
        '9': 'INTEGER15',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'}, 
    'INTEGER15': {
        '0': 'BADTOKEN', 
        '1': 'BADTOKEN', 
        '2': 'BADTOKEN', 
        '3': 'BADTOKEN', 
        '4': 'BADTOKEN', 
        '5': 'BADTOKEN', 
        '6': 'BADTOKEN', 
        '7': 'BADTOKEN', 
        '8': 'BADTOKEN', 
        '9': 'BADTOKEN',
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN',
        'UNDERSCORE': 'BADTOKEN'},
    'OPERATOR':{
        'INITIAL':'OPERATOR'},
    'SY_OP':{
        'INITIAL':'SY_OP'},
    'IDENT':{
        'SY_LPAREN':'INITIAL',
        'SY_RPAREN':'INITIAL',
        'SY_LBRACKET':'INITIAL',
        'SY_RBRACKET':'INITIAL',
        'SY_LBRACE':'INITIAL',
        'SY_RBRACE':'INITIAL',
        'SY_EQ':'INITIAL',
        'SY_MINUS':'INITIAL',
        'SY_SEMI':'INITIAL',
        'SY_PERIOD':'INITIAL',
        'SY_NOT':'INITIAL',
        'SY_COMMA':'INITIAL',
        'SY_OP':'INITIAL',
        'SPACE':'INITIAL',
        'NEWLINE':'INITIAL',
        '*':'IDENT'},
    'BADTOKEN':{
        'INITIAL':'BADTOKEN',
        '0':'BADTOKEN',
        '1':'BADTOKEN',
        '2':'BADTOKEN',
        '3':'BADTOKEN',
        '4':'BADTOKEN',
        '5':'BADTOKEN',
        '6':'BADTOKEN',
        '7':'BADTOKEN',
        '8':'BADTOKEN',
        '9':'BADTOKEN',        
        'a': 'BADTOKEN',
        'b': 'BADTOKEN',
        'c': 'BADTOKEN',
        'd': 'BADTOKEN',
        'e': 'BADTOKEN',
        'f': 'BADTOKEN',
        'g': 'BADTOKEN',
        'h': 'BADTOKEN',
        'i': 'BADTOKEN',
        'j': 'BADTOKEN',
        'k': 'BADTOKEN',
        'l': 'BADTOKEN',
        'm': 'BADTOKEN',
        'n': 'BADTOKEN',
        'o': 'BADTOKEN',
        'p': 'BADTOKEN',
        'q': 'BADTOKEN',
        'r': 'BADTOKEN',
        's': 'BADTOKEN',
        't': 'BADTOKEN',
        'u': 'BADTOKEN',
        'v': 'BADTOKEN',
        'w': 'BADTOKEN',
        'x': 'BADTOKEN',
        'y': 'BADTOKEN',
        'z': 'BADTOKEN',
        'IDENT':'BADTOKEN',
        'BADTOKEN':'BADTOKEN',
        'A': 'BADTOKEN',
        'B': 'BADTOKEN',
        'C': 'BADTOKEN',
        'D': 'BADTOKEN',
        'E': 'BADTOKEN',
        'F': 'BADTOKEN',
        'G': 'BADTOKEN',
        'H': 'BADTOKEN',
        'I': 'BADTOKEN',
        'J': 'BADTOKEN',
        'K': 'BADTOKEN',
        'L': 'BADTOKEN',
        'M': 'BADTOKEN',
        'N': 'BADTOKEN',
        'O': 'BADTOKEN',
        'P': 'BADTOKEN',
        'Q': 'BADTOKEN',
        'R': 'BADTOKEN',
        'S': 'BADTOKEN',
        'T': 'BADTOKEN',
        'U': 'BADTOKEN',
        'V': 'BADTOKEN',
        'W': 'BADTOKEN',
        'X': 'BADTOKEN',
        'Y': 'BADTOKEN',
        'Z': 'BADTOKEN'},
    'SPACE':{
        'INITIAL':'SPACE'},
    'NEWLINE':{
        'INITIAL':'NEWLINE'},
    'SLASH':{
        'INITIAL':'SY_OP',
        'SLASH':'COMMENT_EOL',
        'STAR':'COMMENT_BLK_BODY'},
    'STAR':{
        'INITIAL':'SY_OP',
        'SLASH':'COMMENT_BLK_BODY'},
    'COMMENT_EOL':{
        'INITIAL':'COMMENT_EOL',
        'NEWLINE':'INITIAL',
        '*':'COMMENT_EOL'},
    'COMMENT_BLK_BODY':{
        'INITIAL':'COMMENT_BLK_BODY',
        'STAR':'COMMENT_STAR',
        '*':'COMMENT_BLK_BODY'
        },
    'COMMENT_STAR':{
        '*':'COMMENT_BLK_BODY',
        'STAR':'COMMENT_STAR',
        'SLASH':'COMMENT_BLK'},
    'SY_LPAREN':{'INITIAL':'SY_LPAREN'},
    'SY_RPAREN':{'INITIAL':'SY_RPAREN'},
    'SY_LBRACKET':{'INITIAL':'SY_LBRACKET'},
    'SY_RBRACKET':{'INITIAL':'SY_RBRACKET'},
    'SY_LBRACE':{'INITIAL':'SY_LBRACE'},
    'SY_RBRACE':{'INITIAL':'SY_RBRACE'},
    'SY_EQ':{'INITIAL':'SY_EQ'},
    'SY_MINUS':{'INITIAL':'SY_MINUS'},
    'SY_SEMI':{'INITIAL':'SY_SEMI'},
    'SY_PERIOD':{'INITIAL':'SY_PERIOD'},
    'SY_NOT':{'INITIAL':'SY_NOT'},
    'SY_COMMA':{'INITIAL':'SY_COMMA'}
}
